apiVersion: apps/v1

kind: Deployment

metadata:
  name: wordpress-mysql
  labels:
    app: wordpress

spec:
  selector:
    matchLabels:
      app: wordpress
      tier: backend

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: wordpress
        tier: backend
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_USER
          value: wordpressuser
        - name: MYSQL_PASSWORD
          value: wordpresspass
        - name: MYSQL_ROOT_PASSWORD
          value: wordpressrootpass
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
         claimName: mysql-pv-claim