apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  storageclass: manual 
  capacity
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath::
   path: /c/Users/Iria/Desktop/prueba/mysql