apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: backend
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: backend
  clusterIP: None